language: node_js
install:
  - npm install --save-dev babel-register
  - npm install --save-dev babel-preset-env
  - npm install --save-dev babel-plugin-transform-runtime
  - npm install --save babel-runtime
  - npm install jasmine
  - npm install -g jasmine
script:
  - npm test
